config/routes.rb
Testy::Application.routes.draw do
  resources :posts
  resources :users

   root to: 'hello#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  validates_length_of :login, within: 2..16
  validates_presence_of :password
  validates_format_of :email, with: /\A[^@]+@\S+\z/

  has_many :posts

  def password=(original_password)

	#we started off doing this:
       	#salt = BCrypt::Engine.generate_salt
	#encrypted = BCrypt::Engine.hash_secret(original_password, salt)
	#but are changing now to instead use BCrypt::Password
	encrypted = BCrypt::Password.create(original_password) #this returns a BCrypt::Password object

	# har har har wouldn't it be funny if we did this (infinitely recurses on itself):
	# self.password = encrypted

	super(encrypted.to_s) #and we need to convert that BCrypt::Password object to a string.
	#which actually is just going to do this but is a more consistent way of expressing it:
	#self.write_attribute(:password, encrypted)

  end

  def self.authenticate(login, plaintext)
	# look up the user with that login
	# check that the passwords match
	# return the User if so, or nil if not.
	user = User.where(login: login).first
	if user   # because if we found the user, this is not nil, otherwise it is nil and will evaluate to false
		encrypted = BCrypt::Password.new(user.password)
		if encrypted == plaintext # well that is an odd thing to write but it should work
			user 	# returns this since it's the last value in the routine. 
			# you can use 'return' if you  really want
#		else				saying 'else nil' is not necessary but you can if you want.
#			nil			The if statement will return nil if the condition evals false.
		end
	end
  end

end

# @user.password = "pie"

# "pie" + "dqw7ad7" = "piedqw7ad7"
# dqw7ad7dwhii7ddh7is7isef7ihhis7e

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# do nothing!
	def new
	end

	def create
  		@post = Post.new(post_params)
  		@post.save
  		redirect_to @post
	end

	def show
  		@post = Post.find(params[:id])
	end

	def index
		@posts = Post.all
	end
 
	private
  		def post_params
    		  params.require(:post).permit(:title, :text)
  		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	  @user = User.new
	end

	def create
		user_params = params.require(:user).permit(:login, :email, :password)
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Created a user for you! That's special."
			redirect_to @user
		else
			flash[:alert] = "Your user sucks: #{@user.errors.full_messages.join(', ')}"
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end


	def index
		@user = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/hello/index.html.erb
<h1>HEY MAUS! GOOD CONFIGURIN'!</h1>
<p>You are looking at app/views/hello/index.html.erb and you love it.</p>
<%= link_to "Stuff Poster", controller: "posts" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <div class="flash flash-notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash flash-alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
 
<%= link_to 'New Thing', new_post_path %>

<table>
  <tr>
    <th>Date</th>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.updated_at %></td>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>Post New Item</h1>
<p>Here is where you're going to create a new item.</p>
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back...', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<%= link_to 'Back...', posts_path %>

app/views/users/index.html.erb
<h1>Listing Users (why would I do that)</h1>

<%= link_to 'New User', new_user_path %>

<table>
	<tr>
		<th>Login Name</th>
		<th>Email</th>
	</tr>

	<% @users.each do |user| %>
		<tr>
			<td><%= user.login %></td>
			<td><%= user.email %></td>
		</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<h1>I LIKE PIE</h1>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>User Name:</strong>
  <%= @user.login %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Back to Posts', posts_path %>